services:
  - type: web
    name: marketplace-app
    runtime: docker
    plan: free
    region: frankfurt
    dockerContext: .
    dockerfilePath: Dockerfile

    envVars:
      # ① raw (non-SSL) URI inside Render's private network
      - key: DATABASE_URL
        fromDatabase:
          name: marketplace-db
          property: internalConnectionString 

      # ② credentials for HikariCP
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: marketplace-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: marketplace-db
          property: password

      # ③ keep Render from port-scanning
      - key: PORT
        value: "8080"
