databases:
  - name: marketplace-db
    databaseName: siwmarketplace
    plan: free
    region: frankfurt

services:
  - type: web
    name: marketplace-app
    runtime: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free
    region: frankfurt

    envVars:
      # full JDBC URL (note the jdbc: prefix)
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://marketplace-db:5432/siwmarketplace"

      # credentials come directly from the database Render just created
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: marketplace-db
          property: user

      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: marketplace-db
          property: password

      # keep Render from guessing the port
      - key: PORT
        value: "8080"