databases:
  - name: marketplace-db
    databaseName: siwmarketplace
    plan: free
    region: frankfurt

services:
  - type: web
    name: marketplace-app
    runtime: docker
    plan: free
    region: frankfurt
    dockerContext: .
    dockerfilePath: Dockerfile

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: marketplace-db
          property: connectionString

      - key: PORT
        value: "8080"
